version: '3.9'

services:
  drupal:
    image: custom-drupal
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  database:
    image: postgres:14-alpine
    container_name: database
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  database: